export const mockTransactions = [
  {
    id: "t1",
    date: "May 9, 2025",
    merchant: "Whole Foods Market",
    description: "Groceries",
    amount: 89.47,
    type: "expense",
    category: "groceries",
  },
  {
    id: "t2",
    date: "May 8, 2025",
    merchant: "Netflix",
    description: "Monthly subscription",
    amount: 15.99,
    type: "expense",
    category: "entertainment",
  },
  {
    id: "t3",
    date: "May 7, 2025",
    merchant: "Shell",
    description: "Gas station",
    amount: 45.23,
    type: "expense",
    category: "transportation",
  },
  {
    id: "t4",
    date: "May 7, 2025",
    merchant: "Starbucks",
    description: "Coffee",
    amount: 5.65,
    type: "expense",
    category: "dining",
  },
  {
    id: "t5",
    date: "May 6, 2025",
    merchant: "Amazon",
    description: "Electronics",
    amount: 129.99,
    type: "expense",
    category: "shopping",
  },
  {
    id: "t6",
    date: "May 5, 2025",
    merchant: "Acme Corp",
    description: "Salary deposit",
    amount: 2375.0,
    type: "income",
    category: "income",
  },
  {
    id: "t7",
    date: "May 5, 2025",
    merchant: "AT&T",
    description: "Phone bill",
    amount: 85.0,
    type: "expense",
    category: "utilities",
  },
  {
    id: "t8",
    date: "May 4, 2025",
    merchant: "CVS Pharmacy",
    description: "Medications",
    amount: 32.5,
    type: "expense",
    category: "health",
  },
  {
    id: "t9",
    date: "May 3, 2025",
    merchant: "AMC Theaters",
    description: "Movie tickets",
    amount: 28.5,
    type: "expense",
    category: "entertainment",
  },
  {
    id: "t10",
    date: "May 2, 2025",
    merchant: "Trader Joe's",
    description: "Groceries",
    amount: 65.78,
    type: "expense",
    category: "groceries",
  },
  {
    id: "t11",
    date: "May 1, 2025",
    merchant: "Chevron",
    description: "Gas station",
    amount: 48.92,
    type: "expense",
    category: "transportation",
  },
  {
    id: "t12",
    date: "Apr 30, 2025",
    merchant: "Chipotle",
    description: "Lunch",
    amount: 12.85,
    type: "expense",
    category: "dining",
  },
  {
    id: "t13",
    date: "Apr 29, 2025",
    merchant: "Spotify",
    description: "Monthly subscription",
    amount: 9.99,
    type: "expense",
    category: "entertainment",
  },
  {
    id: "t14",
    date: "Apr 28, 2025",
    merchant: "Uber",
    description: "Ride share",
    amount: 24.5,
    type: "expense",
    category: "transportation",
  },
  {
    id: "t15",
    date: "Apr 27, 2025",
    merchant: "Target",
    description: "Household items",
    amount: 78.35,
    type: "expense",
    category: "shopping",
  },
  {
    id: "t16",
    date: "Apr 26, 2025",
    merchant: "Vanguard",
    description: "Index fund investment",
    amount: 500.0,
    type: "investment",
    category: "investment",
  },
  {
    id: "t17",
    date: "Apr 20, 2025",
    merchant: "Robinhood",
    description: "Stock purchase",
    amount: 250.0,
    type: "investment",
    category: "investment",
  },
  {
    id: "t18",
    date: "Apr 15, 2025",
    merchant: "Fidelity",
    description: "401(k) contribution",
    amount: 350.0,
    type: "investment",
    category: "investment",
  },
];

// Mock Budgets
export const mockBudgets = [
  {
    id: "b1",
    category: "Groceries",
    limit: 500.0,
    spent: 320.45,
  },
  {
    id: "b2",
    category: "Dining Out",
    limit: 300.0,
    spent: 275.8,
  },
  {
    id: "b3",
    category: "Entertainment",
    limit: 200.0,
    spent: 154.48,
  },
  {
    id: "b4",
    category: "Transportation",
    limit: 250.0,
    spent: 218.65,
  },
  {
    id: "b5",
    category: "Shopping",
    limit: 300.0,
    spent: 329.99,
  },
  {
    id: "b6",
    category: "Utilities",
    limit: 400.0,
    spent: 385.0,
  },
  {
    id: "b7",
    category: "Health",
    limit: 150.0,
    spent: 82.5,
  },
  {
    id: "b8",
    category: "Travel",
    limit: 500.0,
    spent: 0.0,
  },
];

// Mock Accounts
export const mockAccounts = [
  {
    id: "a1",
    name: "Checking Account",
    institution: "Chase Bank",
    type: "Checking",
    balance: 4250.75,
  },
  {
    id: "a2",
    name: "Savings Account",
    institution: "Chase Bank",
    type: "Savings",
    balance: 8329.5,
  },
  {
    id: "a3",
    name: "Credit Card",
    institution: "American Express",
    type: "Credit",
    balance: 1245.89,
  },
  {
    id: "a4",
    name: "Investment Account",
    institution: "Vanguard",
    type: "Investment",
    balance: 32580.25,
  },
  {
    id: "a5",
    name: "401(k)",
    institution: "Fidelity",
    type: "Retirement",
    balance: 85750.0,
  },
];

// Mock Financial Goals
export const mockGoals = [
  {
    id: "g1",
    name: "Emergency Fund",
    target: 10000.0,
    current: 8329.5,
    deadline: "December 2025",
  },
  {
    id: "g2",
    name: "Vacation",
    target: 3000.0,
    current: 1500.0,
    deadline: "August 2025",
  },
  {
    id: "g3",
    name: "New Car",
    target: 25000.0,
    current: 5000.0,
    deadline: "June 2026",
  },
  {
    id: "g4",
    name: "Home Down Payment",
    target: 60000.0,
    current: 15000.0,
    deadline: "January 2027",
  },
];
